# PHP Docker Template 0.1.0

version: "3.9"
services:
  app:
    build: .
    image: app
    container_name: app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"

  admin:
    image: phpmyadmin:5.1.3-apache
    container_name: admin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db

  db:
    image: mariadb:10.7.3-focal
    container_name: db
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_USER=app
      - MARIADB_PASSWORD=PasswordExample
      - MARIADB_DATABASE=app
